---
- name: Deploiement serveur
  hosts: server_test
  collections: 
    - community.docker.docker_image
  gather_facts: true
  become: true
  roles:
  #  - baviae.base
  #  - geerlingguy.docker
    - baviae.server


