---
- name: use a dedicated Ansible module
  hosts: all
  become: true
  vars_files:
    - secret
  tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      apt: upgrade=dist

    - name: installation postgres
      command: sudo docker pull postgres

    - name: install maven
      command: sudo apt install maven -y

    - name : create Data Base and user name passeword And run container
      command: sudo docker run --name postgreDB -p 5432:5432 -e POSTGRES_PASSWORD=1234  -e POSTGRES_USER=baviae -e POSTGRES_DB=ecocom -d postgres

    - name: install java 11
      command: sudo apt install openjdk-11-jre-headless

    - name: build jar de l'apply
      command: mvn -f ./eco-commerce clean install

    - name: build l'image de l'apply java
      command: sudo docker build ./eco-commerce -t java-application

    - name: Lancement du container de l'apply java
      command: sudo docker run --network "host" -p 8080:8080 -d java-application

    - name: build l'image de l'apply angular
      command: sudo docker build ./eco-commerce-front -t app-front

    - name: Lancement du container de l'apply
      command: sudo docker run -p 4200:4200 --name app-fronts --network "host" -d --rm app-front


