---
- name: Check if the postgresql pacakges are installed
  yum:
    name: "{{ postgresql_packages }}"
    state: present

- name: Check if the postgresql librairies are installed
  yum:
    name: "{{ postgresql_python_library }}"
    state: present