---
- name: Installation from repo Ubuntu
  apt:
    name: 
      - python3-docker
      - maven
    state: present

- name: SDK python pour docker
  pip:
    name: docker

- name: git clone du projet
  become: no
  git:
    repo: https://github.com/baviae/fil-rouge.git
    dest: /home/{{ ansible_user }}/fil-rouge
    force: yes

- name: DOCKER - Pull image postgres
  docker_image:
    name: postgres
    source: pull
    state: present

- name: DOCKER - Lancement container postgres
  community.docker.docker_container:
    name: EcoCom-postgres_DB
    image: postgres
    network_mode: host
    env:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_USER: baviae
      POSTGRES_DB: ecocom
    ports:
      - "5432"
    state: started

- name: DOCKER - Build image app-front
  community.docker.docker_image:
    name: app-front
    build: 
      path: /home/{{ ansible_user }}/fil-rouge/eco-commerce-front/
    source: build

- name: DOCKER - Lancement container back-end
  community.docker.docker_container:
    name: EcoCom-Back
    image: aeckelineravalomanda/baviae
    network_mode: host
    ports:
      - "8080"
    detach: yes
    state: started

- name: DOCKER - Lancement container front-end
  community.docker.docker_container:
    name: EcoCom-Front
    image: app-front
    network_mode: host
    ports:
      - "4200"
    state: started

- name: download Filebeat
  shell: curl -L -o /home/{{ ansible_user }}/filebeat.deb -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.12.0-amd64.deb

- name: Installation Filebeat
  shell: sudo dpkg -i /home/{{ ansible_user }}/filebeat.deb

    
  