---
- name: Installation from repo Ubuntu
  apt:
    name:
      - python3-docker
      - maven
    state: present

- name: SDK python pour docker
  pip:
    name: docker

- name: git clone du projet
  become: no
  git:
    repo: https://github.com/baviae/fil-rouge.git
    dest: /home/{{ user_sudo }}/fil-rouge
    force: yes

- name: DOCKER - Pull image postgres
  docker_image:
    name: postgres
    source: pull
    state: present

- name: DOCKER - Lancement container postgres
  community.docker.docker_container:
    name: EcoCom-postgres_DB
    image: postgres
    network_mode: host
    env:
      POSTGRES_PASSWORD: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30636132353462366535303761353938376238343231613736386338623932646533333238623661
          6532303564336430306237626235313165336636333230380a393933656666386133353666656363
          35653538353834313638303766376666376330383961386635656235386433346336376663313835
          6164623731336361370a363338353931666633393730373737323035306566376138313464636138
          3264
      POSTGRES_USER: baviae
      POSTGRES_DB: ecocom
    ports:
      - "5432"
    container_default_behavior: no_defaults
    state: started

- name: buil jar de l'application
  become: no
  shell:
    cmd: "mvn -f /home/{{ user_sudo }}/fil-rouge/eco-commerce clean install"

- name: DOCKER - Build image java-application (back-end)
  community.docker.docker_image:
    name: java-application
    build:
      path: /home/{{ user_sudo }}/fil-rouge/eco-commerce/
    source : build

- name: DOCKER - Build image app-front
  community.docker.docker_image:
    name: app-front
    build:
      path: /home/{{ user_sudo }}/fil-rouge/eco-commerce-front/
    source: build

- name: DOCKER - Lancement container back-end
  community.docker.docker_container:
    name: EcoCom-Back
    image: java-application
    network_mode: host
    #    volume: /home/{{ user_sudo }}/fil-rouge/eco-commerce/:/app
    ports:
      - "8080"
    container_default_behavior: no_defaults
    state: started

- name: DOCKER - Lancement container front-end
  community.docker.docker_container:
    name: EcoCom-Front
    image: app-front
    network_mode: host
    ports:
      - "4200"
    container_default_behavior: no_defaults
    state: started
