---
# vars file for role.docker
dependencies_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - gnupg-agent
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
docker_compose_version: "1.27.4"