spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://170.75.162.111:5432/ecocom
    username: baviae
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#logging:
#  config: src/main/resources/test.xml
