---
- name: Deploiement docker sur serveur
  hosts: all
  #collections: 
  #  - community.docker.docker_image
  gather_facts: yes
  become: yes
  roles:
    - baviae.base
    - geerlingguy.docker
    - baviae.server


