---
- name: Deploiement serveur
  hosts: localhost
    controleur_test:
  collections: 
    - community.docker.docker_image
  gather_facts: yes
  become: yes
  roles:
    - baviae.base
  #  - geerlingguy.docker
  #  - baviae.workstation




