---
- name: Deploiement serveur
  hosts: localhost
  vars:
    user_ssh: ubuntu
    user_sudo: ubuntu
  collections: 
    - community.docker.docker_image
  gather_facts: no
  become: yes
  roles:
    - baviae.base
  #  - geerlingguy.docker
  #  - baviae.workstation




