---
- name: Deploiement serveur
  hosts: localhost
  collections: 
    - community.docker.docker_image
  gather_facts: no
  become: yes
  ansible_sudo_pass: 1234
  roles:
    - baviae.base
    - geerlingguy.docker
    - baviae.workstation




